#!/bin/bash
set -e

if [ ! $# -eq 1 ]
then
    echo "usage $0 [build][upload][deploy]"
    echo -e "\tbuild  - builds tez"
    echo -e "\tupload - uploads tez to HDFS"
    echo -e "\tdeploy - builds and uploads tez"
    exit 1
fi

echo "working directory: /vagrant"
cd /vagrant

if [ ! -e "/vagrant/tez" ]
then
    git clone https://github.com/apache/tez.git
fi

tez_version=0.5.2

cd tez

if [ $1 == "build" -o $1 == "deploy" ]
then
    git fetch origin
    git checkout branch-${tez_version}
    git pull origin branch-${tez_version}
    mvn clean package -DskipTests -Dmaven.repo.local=/vagrant/_m2_local/
fi

if [ $1 == "upload" -o $1 == "deploy" ]
then
    hadoop fs -rm -r -f /apps
    hadoop fs -mkdir /apps
    hadoop fs -copyFromLocal tez-dist/target/tez-${tez_version} /apps/tez
fi
